Update template_actions.yml

diff --git a/.github/workflows/template_actions.yml b/.github/workflows/template_actions.yml
--- a/.github/workflows/template_actions.yml
+++ b/.github/workflows/template_actions.yml
@@ -148,27 +148,27 @@ jobs:
      #     issue-title: "Stack Buckets: Deploying Terraform plan to apply"
           
       - name: 'Terraform Apply for the stack compartments'
-        if: ${{env.PLAN_JOB_ID != '' && env.SKIP_TF_APPLY == '' }}
+        if: ${{env.PLAN_JOB_ID != '' && env.SKIP_TF_APPLY == 'yes' }}
         run: |
           echo "APPLY_JOB_ID=$(/home/runner/bin/oci resource-manager job create-apply-job \
             --execution-plan-strategy FROM_PLAN_JOB_ID \
             --execution-plan-job-id $PLAN_JOB_ID \
             --stack-id $STACK_ID_COMPARTMENTS \
              | jq '.data.id' -r)" >> $GITHUB_ENV
-      - name: 'Wait for Terraform Apply to complete'
-        if: ${{env.APPLY_JOB_ID != ''}}
-        run: |
-          while true
-          do
-            JOB_STATUS=$(/home/runner/bin/oci resource-manager job get --job-id ${{env.APPLY_JOB_ID}}  | jq '.data' | grep lifecycle-state | awk '{print $2}' | tr -d '"' | tr -d ',')
-            if [ "$JOB_STATUS" == "SUCCEEDED" ]; then
-              echo "Terraform Apply: $JOB_STATUS"
-              break
-            elif [ "$JOB_STATUS" == "FAILED" ]; then
-              echo "Terraform Apply: $JOB_STATUS"
-              exit 1
-            else
-              echo "Terraform Apply: $JOB_STATUS"
-              sleep 30
-            fi
-          done
+    #  - name: 'Wait for Terraform Apply to complete'
+    #    if: ${{env.APPLY_JOB_ID != ''}}
+    #    run: |
+    #      while true
+    #      do
+    #        JOB_STATUS=$(/home/runner/bin/oci resource-manager job get --job-id ${{env.APPLY_JOB_ID}}  | jq '.data' | grep lifecycle-state | awk '{print $2}' | tr -d '"' | tr -d ',')
+    #        if [ "$JOB_STATUS" == "SUCCEEDED" ]; then
+    #          echo "Terraform Apply: $JOB_STATUS"
+    #          break
+    #        elif [ "$JOB_STATUS" == "FAILED" ]; then
+   #           echo "Terraform Apply: $JOB_STATUS"
+    #          exit 1
+    #        else
+    #          echo "Terraform Apply: $JOB_STATUS"
+    #          sleep 30
+    #        fi
+    #      done
